# Generated by Django 5.1 on 2024-11-11 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diaryentry_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
